spring.application.name=backEndGimnasioF
spring.datasource.url=jdbc:postgresql://localhost:5432/Gimnasio
spring.datasource.username=postgres
spring.datasource.password=1234

### Para enviar email via GMAIL SMTP
spring.mail.host = smtp.gmail.com
spring.mail.port=587
spring.mail.username=cesar33jverne@gmail.com
spring.mail.password = kkjm tzwi cymo bfwi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
